--liquibase formatted sql

--changeset brunoestrai:1

CREATE TABLE EMPRESTIMOS (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS,
    LIVRO_ID INTEGER NOT NULL REFERENCES LIVROS,
    STATUS INTEGER NOT NULL DEFAULT 1,
    DATA_EMPRESTIMO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_DEVOLUCAO TIMESTAMP
);
